// Generated by sprotodump. DO NOT EDIT!
// source: ./../tool/s2c.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace S2cSprotoType { 
	public class achi : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _csv_id; // tag 0
		public Int64 csv_id {
			get { return _csv_id; }
			set { base.has_field.set_field (0, true); _csv_id = value; }
		}
		public bool HasCsv_id {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _finished; // tag 1
		public Int64 finished {
			get { return _finished; }
			set { base.has_field.set_field (1, true); _finished = value; }
		}
		public bool HasFinished {
			get { return base.has_field.has_field (1); }
		}

		public achi () : base(max_field_count) {}

		public achi (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.csv_id = base.deserialize.read_integer ();
					break;
				case 1:
					this.finished = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.csv_id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.finished, 1);
			}

			return base.serialize.close ();
		}
	}


	public class equipment : SprotoTypeBase {
		private static int max_field_count = 11;
		
		
		private Int64 _csv_id; // tag 0
		public Int64 csv_id {
			get { return _csv_id; }
			set { base.has_field.set_field (0, true); _csv_id = value; }
		}
		public bool HasCsv_id {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _level; // tag 1
		public Int64 level {
			get { return _level; }
			set { base.has_field.set_field (1, true); _level = value; }
		}
		public bool HasLevel {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _combat; // tag 2
		public Int64 combat {
			get { return _combat; }
			set { base.has_field.set_field (2, true); _combat = value; }
		}
		public bool HasCombat {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _defense; // tag 3
		public Int64 defense {
			get { return _defense; }
			set { base.has_field.set_field (3, true); _defense = value; }
		}
		public bool HasDefense {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _critical_hit; // tag 4
		public Int64 critical_hit {
			get { return _critical_hit; }
			set { base.has_field.set_field (4, true); _critical_hit = value; }
		}
		public bool HasCritical_hit {
			get { return base.has_field.has_field (4); }
		}

		private Int64 _king; // tag 5
		public Int64 king {
			get { return _king; }
			set { base.has_field.set_field (5, true); _king = value; }
		}
		public bool HasKing {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _critical_hit_probability; // tag 6
		public Int64 critical_hit_probability {
			get { return _critical_hit_probability; }
			set { base.has_field.set_field (6, true); _critical_hit_probability = value; }
		}
		public bool HasCritical_hit_probability {
			get { return base.has_field.has_field (6); }
		}

		private Int64 _combat_probability; // tag 7
		public Int64 combat_probability {
			get { return _combat_probability; }
			set { base.has_field.set_field (7, true); _combat_probability = value; }
		}
		public bool HasCombat_probability {
			get { return base.has_field.has_field (7); }
		}

		private Int64 _defense_probability; // tag 8
		public Int64 defense_probability {
			get { return _defense_probability; }
			set { base.has_field.set_field (8, true); _defense_probability = value; }
		}
		public bool HasDefense_probability {
			get { return base.has_field.has_field (8); }
		}

		private Int64 _king_probability; // tag 9
		public Int64 king_probability {
			get { return _king_probability; }
			set { base.has_field.set_field (9, true); _king_probability = value; }
		}
		public bool HasKing_probability {
			get { return base.has_field.has_field (9); }
		}

		private Int64 _enhance_success_rate; // tag 10
		public Int64 enhance_success_rate {
			get { return _enhance_success_rate; }
			set { base.has_field.set_field (10, true); _enhance_success_rate = value; }
		}
		public bool HasEnhance_success_rate {
			get { return base.has_field.has_field (10); }
		}

		public equipment () : base(max_field_count) {}

		public equipment (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.csv_id = base.deserialize.read_integer ();
					break;
				case 1:
					this.level = base.deserialize.read_integer ();
					break;
				case 2:
					this.combat = base.deserialize.read_integer ();
					break;
				case 3:
					this.defense = base.deserialize.read_integer ();
					break;
				case 4:
					this.critical_hit = base.deserialize.read_integer ();
					break;
				case 5:
					this.king = base.deserialize.read_integer ();
					break;
				case 6:
					this.critical_hit_probability = base.deserialize.read_integer ();
					break;
				case 7:
					this.combat_probability = base.deserialize.read_integer ();
					break;
				case 8:
					this.defense_probability = base.deserialize.read_integer ();
					break;
				case 9:
					this.king_probability = base.deserialize.read_integer ();
					break;
				case 10:
					this.enhance_success_rate = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.csv_id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.level, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.combat, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.defense, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.critical_hit, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_integer (this.king, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.critical_hit_probability, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_integer (this.combat_probability, 7);
			}

			if (base.has_field.has_field (8)) {
				base.serialize.write_integer (this.defense_probability, 8);
			}

			if (base.has_field.has_field (9)) {
				base.serialize.write_integer (this.king_probability, 9);
			}

			if (base.has_field.has_field (10)) {
				base.serialize.write_integer (this.enhance_success_rate, 10);
			}

			return base.serialize.close ();
		}
	}


	public class finish_achi {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private achi _which; // tag 0
			public achi which {
				get { return _which; }
				set { base.has_field.set_field (0, true); _which = value; }
			}
			public bool HasWhich {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.which = base.deserialize.read_obj<achi> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.which, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _errorcode; // tag 0
			public Int64 errorcode {
				get { return _errorcode; }
				set { base.has_field.set_field (0, true); _errorcode = value; }
			}
			public bool HasErrorcode {
				get { return base.has_field.has_field (0); }
			}

			private string _msg; // tag 1
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (1, true); _msg = value; }
			}
			public bool HasMsg {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.errorcode = base.deserialize.read_integer ();
						break;
					case 1:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.errorcode, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.msg, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class kungfu_content : SprotoTypeBase {
		private static int max_field_count = 5;
		
		
		private Int64 _csv_id; // tag 1
		public Int64 csv_id {
			get { return _csv_id; }
			set { base.has_field.set_field (0, true); _csv_id = value; }
		}
		public bool HasCsv_id {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _k_level; // tag 2
		public Int64 k_level {
			get { return _k_level; }
			set { base.has_field.set_field (1, true); _k_level = value; }
		}
		public bool HasK_level {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _k_type; // tag 3
		public Int64 k_type {
			get { return _k_type; }
			set { base.has_field.set_field (2, true); _k_type = value; }
		}
		public bool HasK_type {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _k_sp_num; // tag 4
		public Int64 k_sp_num {
			get { return _k_sp_num; }
			set { base.has_field.set_field (3, true); _k_sp_num = value; }
		}
		public bool HasK_sp_num {
			get { return base.has_field.has_field (3); }
		}

		public kungfu_content () : base(max_field_count) {}

		public kungfu_content (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 1:
					this.csv_id = base.deserialize.read_integer ();
					break;
				case 2:
					this.k_level = base.deserialize.read_integer ();
					break;
				case 3:
					this.k_type = base.deserialize.read_integer ();
					break;
				case 4:
					this.k_sp_num = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.csv_id, 1);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.k_level, 2);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.k_type, 3);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.k_sp_num, 4);
			}

			return base.serialize.close ();
		}
	}


	public class lilian_update {
	
		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _errorcode; // tag 0
			public Int64 errorcode {
				get { return _errorcode; }
				set { base.has_field.set_field (0, true); _errorcode = value; }
			}
			public bool HasErrorcode {
				get { return base.has_field.has_field (0); }
			}

			private string _msg; // tag 1
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (1, true); _msg = value; }
			}
			public bool HasMsg {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.errorcode = base.deserialize.read_integer ();
						break;
					case 1:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.errorcode, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.msg, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class login {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private user _u; // tag 0
			public user u {
				get { return _u; }
				set { base.has_field.set_field (0, true); _u = value; }
			}
			public bool HasU {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.u = base.deserialize.read_obj<user> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.u, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class mail {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 4;
			
			
			private Int64 _from; // tag 0
			public Int64 from {
				get { return _from; }
				set { base.has_field.set_field (0, true); _from = value; }
			}
			public bool HasFrom {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _to; // tag 1
			public Int64 to {
				get { return _to; }
				set { base.has_field.set_field (1, true); _to = value; }
			}
			public bool HasTo {
				get { return base.has_field.has_field (1); }
			}

			private string _head; // tag 2
			public string head {
				get { return _head; }
				set { base.has_field.set_field (2, true); _head = value; }
			}
			public bool HasHead {
				get { return base.has_field.has_field (2); }
			}

			private string _msg; // tag 3
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (3, true); _msg = value; }
			}
			public bool HasMsg {
				get { return base.has_field.has_field (3); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.from = base.deserialize.read_integer ();
						break;
					case 1:
						this.to = base.deserialize.read_integer ();
						break;
					case 2:
						this.head = base.deserialize.read_string ();
						break;
					case 3:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.from, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.to, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_string (this.head, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_string (this.msg, 3);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _errorcode; // tag 0
			public Int64 errorcode {
				get { return _errorcode; }
				set { base.has_field.set_field (0, true); _errorcode = value; }
			}
			public bool HasErrorcode {
				get { return base.has_field.has_field (0); }
			}

			private string _msg; // tag 1
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (1, true); _msg = value; }
			}
			public bool HasMsg {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.errorcode = base.deserialize.read_integer ();
						break;
					case 1:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.errorcode, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.msg, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class package : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _type; // tag 0
		public Int64 type {
			get { return _type; }
			set { base.has_field.set_field (0, true); _type = value; }
		}
		public bool HasType {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _session; // tag 1
		public Int64 session {
			get { return _session; }
			set { base.has_field.set_field (1, true); _session = value; }
		}
		public bool HasSession {
			get { return base.has_field.has_field (1); }
		}

		public package () : base(max_field_count) {}

		public package (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.type = base.deserialize.read_integer ();
					break;
				case 1:
					this.session = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.type, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.session, 1);
			}

			return base.serialize.close ();
		}
	}


	public class role : SprotoTypeBase {
		private static int max_field_count = 14;
		
		
		private Int64 _csv_id; // tag 0
		public Int64 csv_id {
			get { return _csv_id; }
			set { base.has_field.set_field (0, true); _csv_id = value; }
		}
		public bool HasCsv_id {
			get { return base.has_field.has_field (0); }
		}

		private bool _is_possessed; // tag 1
		public bool is_possessed {
			get { return _is_possessed; }
			set { base.has_field.set_field (1, true); _is_possessed = value; }
		}
		public bool HasIs_possessed {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _star; // tag 2
		public Int64 star {
			get { return _star; }
			set { base.has_field.set_field (2, true); _star = value; }
		}
		public bool HasStar {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _u_us_prop_num; // tag 3
		public Int64 u_us_prop_num {
			get { return _u_us_prop_num; }
			set { base.has_field.set_field (3, true); _u_us_prop_num = value; }
		}
		public bool HasU_us_prop_num {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _property_id1; // tag 4
		public Int64 property_id1 {
			get { return _property_id1; }
			set { base.has_field.set_field (4, true); _property_id1 = value; }
		}
		public bool HasProperty_id1 {
			get { return base.has_field.has_field (4); }
		}

		private Int64 _value1; // tag 5
		public Int64 value1 {
			get { return _value1; }
			set { base.has_field.set_field (5, true); _value1 = value; }
		}
		public bool HasValue1 {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _property_id2; // tag 6
		public Int64 property_id2 {
			get { return _property_id2; }
			set { base.has_field.set_field (6, true); _property_id2 = value; }
		}
		public bool HasProperty_id2 {
			get { return base.has_field.has_field (6); }
		}

		private Int64 _value2; // tag 7
		public Int64 value2 {
			get { return _value2; }
			set { base.has_field.set_field (7, true); _value2 = value; }
		}
		public bool HasValue2 {
			get { return base.has_field.has_field (7); }
		}

		private Int64 _property_id3; // tag 8
		public Int64 property_id3 {
			get { return _property_id3; }
			set { base.has_field.set_field (8, true); _property_id3 = value; }
		}
		public bool HasProperty_id3 {
			get { return base.has_field.has_field (8); }
		}

		private Int64 _value3; // tag 9
		public Int64 value3 {
			get { return _value3; }
			set { base.has_field.set_field (9, true); _value3 = value; }
		}
		public bool HasValue3 {
			get { return base.has_field.has_field (9); }
		}

		private Int64 _property_id4; // tag 10
		public Int64 property_id4 {
			get { return _property_id4; }
			set { base.has_field.set_field (10, true); _property_id4 = value; }
		}
		public bool HasProperty_id4 {
			get { return base.has_field.has_field (10); }
		}

		private Int64 _value4; // tag 11
		public Int64 value4 {
			get { return _value4; }
			set { base.has_field.set_field (11, true); _value4 = value; }
		}
		public bool HasValue4 {
			get { return base.has_field.has_field (11); }
		}

		private Int64 _property_id5; // tag 12
		public Int64 property_id5 {
			get { return _property_id5; }
			set { base.has_field.set_field (12, true); _property_id5 = value; }
		}
		public bool HasProperty_id5 {
			get { return base.has_field.has_field (12); }
		}

		private Int64 _value5; // tag 13
		public Int64 value5 {
			get { return _value5; }
			set { base.has_field.set_field (13, true); _value5 = value; }
		}
		public bool HasValue5 {
			get { return base.has_field.has_field (13); }
		}

		public role () : base(max_field_count) {}

		public role (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.csv_id = base.deserialize.read_integer ();
					break;
				case 1:
					this.is_possessed = base.deserialize.read_boolean ();
					break;
				case 2:
					this.star = base.deserialize.read_integer ();
					break;
				case 3:
					this.u_us_prop_num = base.deserialize.read_integer ();
					break;
				case 4:
					this.property_id1 = base.deserialize.read_integer ();
					break;
				case 5:
					this.value1 = base.deserialize.read_integer ();
					break;
				case 6:
					this.property_id2 = base.deserialize.read_integer ();
					break;
				case 7:
					this.value2 = base.deserialize.read_integer ();
					break;
				case 8:
					this.property_id3 = base.deserialize.read_integer ();
					break;
				case 9:
					this.value3 = base.deserialize.read_integer ();
					break;
				case 10:
					this.property_id4 = base.deserialize.read_integer ();
					break;
				case 11:
					this.value4 = base.deserialize.read_integer ();
					break;
				case 12:
					this.property_id5 = base.deserialize.read_integer ();
					break;
				case 13:
					this.value5 = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.csv_id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_boolean (this.is_possessed, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.star, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.u_us_prop_num, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.property_id1, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_integer (this.value1, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.property_id2, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_integer (this.value2, 7);
			}

			if (base.has_field.has_field (8)) {
				base.serialize.write_integer (this.property_id3, 8);
			}

			if (base.has_field.has_field (9)) {
				base.serialize.write_integer (this.value3, 9);
			}

			if (base.has_field.has_field (10)) {
				base.serialize.write_integer (this.property_id4, 10);
			}

			if (base.has_field.has_field (11)) {
				base.serialize.write_integer (this.value4, 11);
			}

			if (base.has_field.has_field (12)) {
				base.serialize.write_integer (this.property_id5, 12);
			}

			if (base.has_field.has_field (13)) {
				base.serialize.write_integer (this.value5, 13);
			}

			return base.serialize.close ();
		}
	}


	public class user : SprotoTypeBase {
		private static int max_field_count = 22;
		
		
		private string _uname; // tag 0
		public string uname {
			get { return _uname; }
			set { base.has_field.set_field (0, true); _uname = value; }
		}
		public bool HasUname {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _uviplevel; // tag 1
		public Int64 uviplevel {
			get { return _uviplevel; }
			set { base.has_field.set_field (1, true); _uviplevel = value; }
		}
		public bool HasUviplevel {
			get { return base.has_field.has_field (1); }
		}

		private bool _config_sound; // tag 2
		public bool config_sound {
			get { return _config_sound; }
			set { base.has_field.set_field (2, true); _config_sound = value; }
		}
		public bool HasConfig_sound {
			get { return base.has_field.has_field (2); }
		}

		private bool _config_music; // tag 3
		public bool config_music {
			get { return _config_music; }
			set { base.has_field.set_field (3, true); _config_music = value; }
		}
		public bool HasConfig_music {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _avatar; // tag 4
		public Int64 avatar {
			get { return _avatar; }
			set { base.has_field.set_field (4, true); _avatar = value; }
		}
		public bool HasAvatar {
			get { return base.has_field.has_field (4); }
		}

		private string _sign; // tag 5
		public string sign {
			get { return _sign; }
			set { base.has_field.set_field (5, true); _sign = value; }
		}
		public bool HasSign {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _c_role_id; // tag 6
		public Int64 c_role_id {
			get { return _c_role_id; }
			set { base.has_field.set_field (6, true); _c_role_id = value; }
		}
		public bool HasC_role_id {
			get { return base.has_field.has_field (6); }
		}

		private Int64 _level; // tag 7
		public Int64 level {
			get { return _level; }
			set { base.has_field.set_field (7, true); _level = value; }
		}
		public bool HasLevel {
			get { return base.has_field.has_field (7); }
		}

		private Int64 _recharge_rmb; // tag 8
		public Int64 recharge_rmb {
			get { return _recharge_rmb; }
			set { base.has_field.set_field (8, true); _recharge_rmb = value; }
		}
		public bool HasRecharge_rmb {
			get { return base.has_field.has_field (8); }
		}

		private Int64 _recharge_diamond; // tag 9
		public Int64 recharge_diamond {
			get { return _recharge_diamond; }
			set { base.has_field.set_field (9, true); _recharge_diamond = value; }
		}
		public bool HasRecharge_diamond {
			get { return base.has_field.has_field (9); }
		}

		private Int64 _uvip_progress; // tag 10
		public Int64 uvip_progress {
			get { return _uvip_progress; }
			set { base.has_field.set_field (10, true); _uvip_progress = value; }
		}
		public bool HasUvip_progress {
			get { return base.has_field.has_field (10); }
		}

		private Int64 _cp_hanging_id; // tag 11
		public Int64 cp_hanging_id {
			get { return _cp_hanging_id; }
			set { base.has_field.set_field (11, true); _cp_hanging_id = value; }
		}
		public bool HasCp_hanging_id {
			get { return base.has_field.has_field (11); }
		}

		private Int64 _uexp; // tag 12
		public Int64 uexp {
			get { return _uexp; }
			set { base.has_field.set_field (12, true); _uexp = value; }
		}
		public bool HasUexp {
			get { return base.has_field.has_field (12); }
		}

		private Int64 _gold; // tag 13
		public Int64 gold {
			get { return _gold; }
			set { base.has_field.set_field (13, true); _gold = value; }
		}
		public bool HasGold {
			get { return base.has_field.has_field (13); }
		}

		private Int64 _diamond; // tag 14
		public Int64 diamond {
			get { return _diamond; }
			set { base.has_field.set_field (14, true); _diamond = value; }
		}
		public bool HasDiamond {
			get { return base.has_field.has_field (14); }
		}

		private Int64 _love; // tag 15
		public Int64 love {
			get { return _love; }
			set { base.has_field.set_field (15, true); _love = value; }
		}
		public bool HasLove {
			get { return base.has_field.has_field (15); }
		}

		private List<equipment> _equipment_list; // tag 16
		public List<equipment> equipment_list {
			get { return _equipment_list; }
			set { base.has_field.set_field (16, true); _equipment_list = value; }
		}
		public bool HasEquipment_list {
			get { return base.has_field.has_field (16); }
		}

		private List<kungfu_content> _kungfu_list; // tag 17
		public List<kungfu_content> kungfu_list {
			get { return _kungfu_list; }
			set { base.has_field.set_field (17, true); _kungfu_list = value; }
		}
		public bool HasKungfu_list {
			get { return base.has_field.has_field (17); }
		}

		private List<role> _rolelist; // tag 18
		public List<role> rolelist {
			get { return _rolelist; }
			set { base.has_field.set_field (18, true); _rolelist = value; }
		}
		public bool HasRolelist {
			get { return base.has_field.has_field (18); }
		}

		private Int64 _cp_chapter; // tag 19
		public Int64 cp_chapter {
			get { return _cp_chapter; }
			set { base.has_field.set_field (19, true); _cp_chapter = value; }
		}
		public bool HasCp_chapter {
			get { return base.has_field.has_field (19); }
		}

		private Int64 _lilian_level; // tag 20
		public Int64 lilian_level {
			get { return _lilian_level; }
			set { base.has_field.set_field (20, true); _lilian_level = value; }
		}
		public bool HasLilian_level {
			get { return base.has_field.has_field (20); }
		}

		private Int64 _ara_rnk; // tag 21
		public Int64 ara_rnk {
			get { return _ara_rnk; }
			set { base.has_field.set_field (21, true); _ara_rnk = value; }
		}
		public bool HasAra_rnk {
			get { return base.has_field.has_field (21); }
		}

		public user () : base(max_field_count) {}

		public user (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.uname = base.deserialize.read_string ();
					break;
				case 1:
					this.uviplevel = base.deserialize.read_integer ();
					break;
				case 2:
					this.config_sound = base.deserialize.read_boolean ();
					break;
				case 3:
					this.config_music = base.deserialize.read_boolean ();
					break;
				case 4:
					this.avatar = base.deserialize.read_integer ();
					break;
				case 5:
					this.sign = base.deserialize.read_string ();
					break;
				case 6:
					this.c_role_id = base.deserialize.read_integer ();
					break;
				case 7:
					this.level = base.deserialize.read_integer ();
					break;
				case 8:
					this.recharge_rmb = base.deserialize.read_integer ();
					break;
				case 9:
					this.recharge_diamond = base.deserialize.read_integer ();
					break;
				case 10:
					this.uvip_progress = base.deserialize.read_integer ();
					break;
				case 11:
					this.cp_hanging_id = base.deserialize.read_integer ();
					break;
				case 12:
					this.uexp = base.deserialize.read_integer ();
					break;
				case 13:
					this.gold = base.deserialize.read_integer ();
					break;
				case 14:
					this.diamond = base.deserialize.read_integer ();
					break;
				case 15:
					this.love = base.deserialize.read_integer ();
					break;
				case 16:
					this.equipment_list = base.deserialize.read_obj_list<equipment> ();
					break;
				case 17:
					this.kungfu_list = base.deserialize.read_obj_list<kungfu_content> ();
					break;
				case 18:
					this.rolelist = base.deserialize.read_obj_list<role> ();
					break;
				case 19:
					this.cp_chapter = base.deserialize.read_integer ();
					break;
				case 20:
					this.lilian_level = base.deserialize.read_integer ();
					break;
				case 21:
					this.ara_rnk = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_string (this.uname, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.uviplevel, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_boolean (this.config_sound, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_boolean (this.config_music, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.avatar, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_string (this.sign, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.c_role_id, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_integer (this.level, 7);
			}

			if (base.has_field.has_field (8)) {
				base.serialize.write_integer (this.recharge_rmb, 8);
			}

			if (base.has_field.has_field (9)) {
				base.serialize.write_integer (this.recharge_diamond, 9);
			}

			if (base.has_field.has_field (10)) {
				base.serialize.write_integer (this.uvip_progress, 10);
			}

			if (base.has_field.has_field (11)) {
				base.serialize.write_integer (this.cp_hanging_id, 11);
			}

			if (base.has_field.has_field (12)) {
				base.serialize.write_integer (this.uexp, 12);
			}

			if (base.has_field.has_field (13)) {
				base.serialize.write_integer (this.gold, 13);
			}

			if (base.has_field.has_field (14)) {
				base.serialize.write_integer (this.diamond, 14);
			}

			if (base.has_field.has_field (15)) {
				base.serialize.write_integer (this.love, 15);
			}

			if (base.has_field.has_field (16)) {
				base.serialize.write_obj (this.equipment_list, 16);
			}

			if (base.has_field.has_field (17)) {
				base.serialize.write_obj (this.kungfu_list, 17);
			}

			if (base.has_field.has_field (18)) {
				base.serialize.write_obj (this.rolelist, 18);
			}

			if (base.has_field.has_field (19)) {
				base.serialize.write_integer (this.cp_chapter, 19);
			}

			if (base.has_field.has_field (20)) {
				base.serialize.write_integer (this.lilian_level, 20);
			}

			if (base.has_field.has_field (21)) {
				base.serialize.write_integer (this.ara_rnk, 21);
			}

			return base.serialize.close ();
		}
	}


}

